export const invalidEmail: string = "You have entered an invalid email address!";
export const emptyField: string = "Field is empty";
export const invalidPhone: string = "Not a valid phone number";
export const weakPassword = "Password is weak must be at least 8 character long.";
export const passwordNotMatchToConfirmPassword: string = "Password and confirm Password Doesn't match.";
export const incorrectPassword: string = "Old Password entered is wrong.";
export const sameToOldPass: string = "Old password and new password can't be same please choose a different password.";
export const regexToTestEmail: RegExp = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
export const chooseFirst: string = "Choose first";
export const productFinished: string = "Products finished."